spring.application.name=Day1_ConnectDB
spring.datasource.url=jdbc:mysql://localhost:3306/identity_service
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
server.servlet.context-path=/identity
# sign key for JWT
jwt.signing.key=45e80b0aa04f55c3c21b4a52eafa791b

